---
- name: Install stow
  ansible.builtin.apt:
    name: stow

- name: Remove files that will conflict with Stow
  loop:
    - .bashrc
    - .profile
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent

- name: Run stow
  ansible.builtin.command: "stow . --target {{ ansible_env.HOME }} --verbose=2"
  register: result
  changed_when: 'result.stderr is search("Link: ")'
